[workspace]
resolver = "2"
members = ["console/backend", "runner", "serial-protocol", "simulator/backend", "simulator/sim_msgs"]
exclude = ["app-sdk", "coproc-embassy", "example-apps", "simulator/frontend", "console/frontend"]
