[package]
name = "megabit-console-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
log = { version = "0.4" }
wasm-bindgen = "0.2"
wasm-logger = { version = "0.2" }
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"