[package]
name = "scrolling-text"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
embedded-graphics = "0.8.1"
extism-pdk = { version = "1.0", no-default-features = true }
megabit-app-sdk = { path = "../../app-sdk" }
