[package]
name = "megabit-runner-msgs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
strum_macros = { version = "0.25" }

[dev-dependencies]
serde_json = "1"
