name: coproc-build

on:
  pull_request:
    paths:
      - 'coproc-embassy/**'
      - '.github/workflows/coproc.yml'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format Nano
        run: cargo fmt --all --check --manifest-path coproc-embassy/nano-ble-rgb/Cargo.toml
      - name: Format Pico
        run: cargo fmt --all --check --manifest-path coproc-embassy/pi-pico-rgb/Cargo.toml
  
  build:
    name: Build firmwares
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv7em-none-eabi,thumbv6m-none-eabi"
      - name: Build Arduino Nano 33 BLE firmware
        run: cargo build --release --manifest-path coproc-embassy/nano-ble-rgb/Cargo.toml --target thumbv7em-none-eabi
      - name: Build Pi Pico firmware
        run: cargo build --release --manifest-path coproc-embassy/pi-pico-rgb/Cargo.toml --target thumbv6m-none-eabi
